<a href="https://colab.research.google.com/github/PANKAJVIRENDRAMODI/tensorflow_learningpath/blob/main/tensorflow_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

In [4]:
!nvidia-smi

Mon Nov 30 17:42:25 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P8    33W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
iprove = tf.constant(1,dtype=tf.int64)
iprove

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [6]:
iprovee = tf.constant([[4,2],[5,6]])
print(iprovee)

tf.Tensor(
[[4 2]
 [5 6]], shape=(2, 2), dtype=int32)


In [7]:
iprovee.numpy()

array([[4, 2],
       [5, 6]], dtype=int32)

In [8]:
print("shape",iprovee.shape)

shape (2, 2)


In [9]:
print(tf.ones(shape=(5,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [10]:
print(tf.zeros(shape=(3,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [11]:
const1 = tf.constant([[2,3,4],[4,5,6]]);tf
const2 = tf.constant([[6,8,1],[2,5,9]]);
result = tf.add(const1,const2)
print(result)

tf.Tensor(
[[ 8 11  5]
 [ 6 10 15]], shape=(2, 3), dtype=int32)


In [12]:
tf.random.normal(shape=(2,3),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.58202946,  0.0129263 ,  0.53165835],
       [-2.219619  ,  0.5000129 , -1.1066787 ]], dtype=float32)>

In [13]:
tf.random.uniform(shape=(8,8,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(8, 8, 2), dtype=int32, numpy=
array([[[3, 3],
        [5, 8],
        [6, 4],
        [7, 5],
        [3, 7],
        [0, 3],
        [1, 0],
        [5, 6]],

       [[6, 9],
        [2, 5],
        [9, 8],
        [2, 6],
        [0, 1],
        [2, 6],
        [6, 6],
        [4, 5]],

       [[1, 0],
        [6, 4],
        [3, 5],
        [3, 0],
        [6, 1],
        [6, 5],
        [7, 5],
        [9, 0]],

       [[7, 4],
        [6, 8],
        [8, 2],
        [1, 8],
        [7, 5],
        [0, 5],
        [9, 7],
        [0, 4]],

       [[5, 6],
        [6, 3],
        [9, 3],
        [5, 6],
        [9, 0],
        [7, 2],
        [1, 0],
        [1, 3]],

       [[6, 5],
        [0, 0],
        [6, 4],
        [0, 8],
        [7, 4],
        [8, 5],
        [7, 5],
        [9, 2]],

       [[9, 5],
        [1, 4],
        [3, 9],
        [3, 9],
        [6, 0],
        [1, 1],
        [1, 4],
        [4, 6]],

       [[9, 6],
        [1, 5],
        [

In [14]:
var1 = tf.Variable(42)
var2 = tf.Variable([[[2,3,4],[3,4,5]],[[3,4,2],[2,3,1]]])
var3 = 43
var1,var2,var3

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[2, 3, 4],
         [3, 4, 5]],
 
        [[3, 4, 2],
         [2, 3, 1]]], dtype=int32)>,
 43)

In [15]:
var_reassign = tf.Variable(56.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=56.0>

In [16]:
initial_vals = tf.random.normal(shape=(2,3))
a = tf.Variable(initial_vals) #constant doesn't work for reassigning
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.82284695,  1.7697489 ,  0.12809676],
       [-1.0408072 ,  1.0875716 , -0.41657472]], dtype=float32)>


In [17]:
tensor = tf.Variable([[[2,3,4],[3,4,5]],[[3,4,2],[2,3,1]]])
print(tensor.shape)
tensor

(2, 2, 3)


<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[2, 3, 4],
        [3, 4, 5]],

       [[3, 4, 2],
        [2, 3, 1]]], dtype=int32)>

In [18]:
tensor1 = tf.reshape(tensor,[2,6])
tensor1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[2, 3, 4, 3, 4, 5],
       [3, 4, 2, 2, 3, 1]], dtype=int32)>

In [19]:
tensor2 = tf.reshape(tensor,[2,6,1,1,1])
tensor3 = tf.reshape(tensor,[2,3,2,1,1,1])
tensor3

<tf.Tensor: shape=(2, 3, 2, 1, 1, 1), dtype=int32, numpy=
array([[[[[[2]]],


         [[[3]]]],



        [[[[4]]],


         [[[3]]]],



        [[[[4]]],


         [[[5]]]]],




       [[[[[3]]],


         [[[4]]]],



        [[[[2]]],


         [[[2]]]],



        [[[[3]]],


         [[[1]]]]]], dtype=int32)>

In [20]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [21]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[2, 3, 4],
        [3, 4, 5]],

       [[3, 4, 2],
        [2, 3, 1]]], dtype=int32)>

In [22]:
tensor[1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 2],
       [2, 3, 1]], dtype=int32)>

In [23]:
tensor[1][0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 2], dtype=int32)>

In [24]:
tensor[1][0][2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [25]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(d)
print(e)

tf.Tensor(
[[1.694314   0.04596312]
 [1.2608608  0.53165674]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3.675386   1.2391059 ]
 [3.0736957  0.48231977]], shape=(2, 2), dtype=float32)


In [26]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  9, 16],
        [ 9, 16, 25]],

       [[ 9, 16,  4],
        [ 4,  9,  1]]], dtype=int32)>

In [27]:
tensormult4 = tensor*4
tensormult4

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 8, 12, 16],
        [12, 16, 20]],

       [[12, 16,  8],
        [ 8, 12,  4]]], dtype=int32)>

In [28]:
matrix_u = tf.constant([[4,7,2]])
matrix_v = tf.constant([[8,3,4]])

In [29]:
tf.matmul(matrix_u,tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[61]], dtype=int32)>

In [30]:
tf.matmul(matrix_v,tf.transpose(matrix_u))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[61]], dtype=int32)>

In [31]:
tf.transpose(matrix_v)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[8],
       [3],
       [4]], dtype=int32)>

In [32]:
varx = [2,3,4,5,6]
vary = 9
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([49, 36, 25, 16,  9], dtype=int32)>

In [33]:
variable1 = tf.Variable([[5,6,7,8],[3,2,7,5]])
checkpoint = tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('/vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
variable1
checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[5, 6, 7, 8],
       [3, 2, 7, 5]], dtype=int32)>
